version: "3"
services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST:     postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB:       mydb
      POSTGRES_USER:     postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy


 # monitoring:
 #   image: "prom/prometheus"
